package com.mnr.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;

@Entity
@SequenceGenerator(name = "emp_seq", sequenceName = "emp_seq", allocationSize = 1, initialValue = 1)
public class Employee {
	@Column(name = "EMP_ID")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "emp_seq")
	@Id
	private int id;
	@Column(name = "EMP_NAME")
	private String name;
	@OneToOne
	/* (mappedBy="employee") */// mappedBy property for bidirectional oneToOne
	@JoinColumn(name = "ACCOUNT_ID")
	// this is for overriding autogenerated column in Employee table
	private SalaryAccount salaryAccount;// @OneToOne

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public SalaryAccount getSalaryAccount() {
		return salaryAccount;
	}

	public void setSalaryAccount(SalaryAccount salaryAccount) {
		this.salaryAccount = salaryAccount;
	}

	@Override
	public String toString() {
		return "Employee [id=" + id + ", name=" + name + ", salaryAccount="
				+ salaryAccount + "]";
	}

}
